---
apiVersion: v1
kind: Namespace
metadata:
  name: myminio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hscv
  namespace: myminio
spec:
  clusterIP: None
  selector:
    app: minio 
  ports:
  - name: api 
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
    
      


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-deploy
  namespace: myminio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio
  serviceName: minio-hscv
  volumeClaimTemplates:              
  - metadata:
      name: data-vol
      namespace: myminio
    spec:
      resources:
        requests:
          storage: 1Gi
      accessModes: [ ReadWriteOncePod ]
      storageClassName: do-block-storage 
  template: 
      metadata:
        labels:
          app: minio
      spec:
        containers:
        - name: minio-container       
          image: minio/minio
          #args: [ "server", "/data", "--console-address", ":9090" ]
          args:
            - server
            - --address=:9000
            - --console-address=:9001
            - http://minio-deploy-{0...2}.minio-hscv.myminio.svc.cluster.local/data
          env:
          - name: MINIO_ROOT_USER
            value: "minioadmin" # Change this to a secure username
          - name: MINIO_ROOT_PASSWORD
            value: "minioadmin" # Change this to a secure password
          ports:
          - containerPort: 9000 # API port
            name: api
          - containerPort: 9001 # Console port
            name: console
          volumeMounts:
          - name: data-vol
            mountPath: /data
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            exec:
              command:
              - /bin/sh
              - -c
              - "mc ready local || exit 1"
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 250Mi



---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: myminio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - name: api 
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: myminio
spec:
  ingressClassName: nginx
  rules:
  - host: data-209.38.58.8.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: api
  - host: console-209.38.58.8.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: console
              
              
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: minio-ha
  namespace: myminio
spec:
  minReplicas: 1
  maxReplicas: 3  
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: StatefulSet
    name: minio-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50 